import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { MemoryStoreService } from '../../../infrastructure/cache/memory-store.service';
import { PlacesService } from './places.service';
import { OverpassClient } from '../infrastructure/enrichment/overpass.client';
import {
  WikipediaClient,
  WIKI_LICENCE,
  WIKI_LICENCE_URL,
} from '../infrastructure/enrichment/wikipedia.client';
import { WikipediaCacheOrmEntity } from '../infrastructure/persistence/wikipedia-cache.orm-entity';
import { WIKI_TITLES } from '../infrastructure/enrichment/wiki-titles.dataset';
import {
  OsmEnrichment,
  PlaceEnrichment,
  WikipediaEnrichment,
} from '../domain/place-enrichment';

const OSM_TTL_SECONDS = 7 * 24 * 60 * 60; // 7 days
const WIKI_TTL_SECONDS = 30 * 24 * 60 * 60; // 30 days

/**
 * Enrichment layer that sits *beside* the PlaceRepositoryPort/Strategy path.
 * It composes live OSM (Overpass) and Wikipedia data for a place, cached in
 * the in-process cache. Every external failure degrades to null for that slice — callers keep
 * their curated mock values, so nothing here is load-bearing.
 */
@Injectable()
export class EnrichmentService {
  private readonly logger = new Logger(EnrichmentService.name);

  constructor(
    private readonly places: PlacesService,
    private readonly overpass: OverpassClient,
    private readonly wikipedia: WikipediaClient,
    private readonly store: MemoryStoreService,
    @InjectRepository(WikipediaCacheOrmEntity)
    private readonly wikiCache: Repository<WikipediaCacheOrmEntity>,
  ) {}

  async getEnrichment(placeId: string): Promise<PlaceEnrichment> {
    const [place] = await this.places.findByIds([placeId]);
    if (!place) return { placeId, osm: null, wikipedia: null };

    const [osm, wiki] = await Promise.all([
      this.osmFor(place.placeId, place.name, place.lat, place.lng),
      this.wikiFor(place.placeId),
    ]);
    return { placeId, osm, wikipedia: wiki };
  }

  private async osmFor(
    placeId: string,
    name: string,
    lat: number,
    lng: number,
  ): Promise<OsmEnrichment | null> {
    return this.cached(
      `enrich:osm:${placeId}`,
      OSM_TTL_SECONDS,
      () => this.overpass.fetchNearbyTags(name, lat, lng),
    );
  }

  /**
   * Titles come from `wiki-titles.dataset.ts`, generated by geosearching each
   * place's own coordinate and confirming the article by name. It replaced a
   * hand-written allowlist of six landmarks — a number chosen when the
   * catalogue held 28 places, and left behind as it grew to 124.
   *
   * A place with no entry still gets no panel. The enrichment is additive and
   * never load-bearing, so absence is a quieter state, not a failure.
   */
  private async wikiFor(placeId: string): Promise<WikipediaEnrichment | null> {
    const title = WIKI_TITLES[placeId];
    if (!title) return null;
    return this.cached(`enrich:wiki:${placeId}`, WIKI_TTL_SECONDS, () =>
      this.wikiFromDbOrNetwork(placeId, title),
    );
  }

  /**
   * The table, then Wikipedia.
   *
   * Read order is memory → database → network, each layer cheaper and shorter
   * lived than the one behind it. The database is what makes a restart free:
   * without it a cold process refetched all hundred-odd articles, and a burst
   * that size is answered with 429s rather than articles.
   *
   * Every database failure here is logged and swallowed. This is a cache in
   * front of an optional panel; a broken cache must degrade to a slower panel,
   * never to a missing one.
   */
  private async wikiFromDbOrNetwork(
    placeId: string,
    title: string,
  ): Promise<WikipediaEnrichment | null> {
    try {
      const row = await this.wikiCache.findOne({ where: { placeId } });
      if (row) {
        return {
          title: row.title,
          summary: row.summary,
          thumbnailUrl: row.thumbnailUrl,
          pageUrl: row.pageUrl,
          attribution: 'Wikipedia',
          licence: WIKI_LICENCE,
          licenceUrl: WIKI_LICENCE_URL,
        };
      }
    } catch (err) {
      this.logger.warn(`Wikipedia cache read failed for ${placeId}: ${String(err)}`);
    }

    const fetched = await this.wikipedia.fetchSummary(title);
    // A miss is not written to the table. The in-process layer already holds
    // misses for a day, and a missing article is usually a mapping to fix
    // rather than a fact to store for a month.
    if (!fetched) return null;

    try {
      await this.wikiCache.save({
        placeId,
        title: fetched.title,
        summary: fetched.summary,
        thumbnailUrl: fetched.thumbnailUrl,
        pageUrl: fetched.pageUrl,
      });
    } catch (err) {
      this.logger.warn(`Wikipedia cache write failed for ${placeId}: ${String(err)}`);
    }
    return fetched;
  }

  /**
   * Read-through in-process cache. Caches both hits and misses (misses briefly, as
   * `null`) so a landmark with no OSM tags doesn't hammer Overpass every load.
   * Cache errors are swallowed — the fetch still runs.
   */
  private async cached<T>(
    key: string,
    ttl: number,
    fetcher: () => Promise<T | null>,
  ): Promise<T | null> {
    try {
      const hit = await this.store.get(key);
      if (hit !== null) return JSON.parse(hit) as T | null;
    } catch (err) {
      this.logger.warn(`Cache read failed for ${key}: ${String(err)}`);
    }

    const value = await fetcher();

    try {
      // Cache a miss for a shorter window (1 day) than a hit.
      const effectiveTtl = value === null ? 24 * 60 * 60 : ttl;
      await this.store.setWithTtl(key, JSON.stringify(value), effectiveTtl);
    } catch (err) {
      this.logger.warn(`Cache write failed for ${key}: ${String(err)}`);
    }
    return value;
  }
}
