import type { HubMeta, Place } from './types';

/**
 * Hub + place data.
 *
 * `PLACES` is shaped exactly like a Google Places API response merged with IBB
 * Open Data (place_id, lat/lng, rating, reviewCount, photo_url, opening_hours,
 * entry fee, museum-pass validity). In production `api.getPlaces()` would call
 * the backend `/api/places` (itself backed by Google Places); here it returns
 * this array so the map works fully offline. Kept in sync with the backend
 * dataset in `pathwise-backend/.../place.dataset.ts`.
 */

export const HUBS: HubMeta[] = [
  {
    id: 'sultanahmet',
    name: 'Sultanahmet & Old City',
    side: 'European',
    blurb: 'Byzantine + Ottoman monuments packed into a walkable peninsula.',
    center: [41.0086, 28.9785],
    accent: '#C56F52',
  },
  {
    id: 'karakoy-galata',
    name: 'Karaköy & Galata',
    side: 'European',
    blurb: 'Galata Tower, third-wave coffee, galleries and baklava.',
    center: [41.0243, 28.9748],
    accent: '#4A7C82',
  },
  {
    id: 'kadikoy-moda',
    name: 'Kadıköy & Moda',
    side: 'Asian',
    blurb: 'The Asian side: markets, meyhanes and a seaside sunset.',
    center: [40.9887, 29.027],
    accent: '#C97B8E',
  },
  {
    id: 'balat-fener',
    name: 'Balat & Fener',
    side: 'European',
    blurb: 'Rainbow houses, antique shops and Orthodox heritage.',
    center: [41.0292, 28.9492],
    accent: '#A87F28',
  },
  {
    id: 'besiktas-bogaz',
    name: 'Beşiktaş & Bosphorus',
    side: 'European',
    blurb: 'Palaces, fish markets and the Bosphorus shoreline.',
    center: [41.0455, 29.0087],
    accent: '#5E8C74',
  },
];

export const HUB_BY_ID: Record<string, HubMeta> = Object.fromEntries(
  HUBS.map((h) => [h.id, h]),
);

// Transit hubs / ferry piers for the start-point selector (IBB Open Data).
export const TRANSIT_HUBS: { label: string; lat: number; lng: number }[] = [
  { label: 'Eminönü Pier', lat: 41.0175, lng: 28.9705 },
  { label: 'Kadıköy Pier', lat: 40.9925, lng: 29.0213 },
  { label: 'Karaköy Pier', lat: 41.0223, lng: 28.9776 },
  { label: 'Sirkeci Marmaray', lat: 41.0138, lng: 28.9772 },
  { label: 'Üsküdar Pier', lat: 41.0255, lng: 29.0148 },
];

export const PLACES: Place[] = [
  // ── Sultanahmet & Old City ──
  { placeId: 'ChIJ-sultanahmet-hagiasophia', name: 'Hagia Sophia', hub: 'sultanahmet', lat: 41.0086, lng: 28.9802, rating: 4.8, reviewCount: 312840, photoUrl: 'https://images.pathwise.mock/hagia-sophia.jpg', category: 'history', interests: ['history', 'photo'], entryFeeTry: 1500, avgFoodCostTry: 0, avgVisitMinutes: 75, openingHours: 'Daily 09:00–19:00', isIndoor: true, isSunsetSpot: false, museumPass: true, localTip: 'Enter from the side gate for the upper gallery — far shorter queue.', neighborhood: 'Sultanahmet', crowdLevel: 'high', safetyScore: 90, isSoloVerified: true, transitNoteBefore: 'T1 tram to Sultanahmet, then a 3-min walk across the park.', insiderTip: 'Go up to the gallery — it is a stone ramp, not stairs. The Deësis mosaic and the 9th-century Viking runes scratched into the marble parapet are up there, and most visitors never climb.', photoGoldenHour: 'Early morning from Sultanahmet Park, before the sun swings behind the domes.', priceTier: 3, emoji: '🕌', source: 'Google Places' },
  { placeId: 'ChIJ-sultanahmet-bluemosque', name: 'Blue Mosque (Sultanahmet Camii)', hub: 'sultanahmet', lat: 41.0054, lng: 28.9768, rating: 4.7, reviewCount: 198220, photoUrl: 'https://images.pathwise.mock/blue-mosque.jpg', category: 'history', interests: ['history', 'photo'], entryFeeTry: 0, avgFoodCostTry: 0, avgVisitMinutes: 45, openingHours: 'Daily, closed to visitors during prayer times', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'Bring a scarf; shoulders and knees must be covered inside.', neighborhood: 'Sultanahmet', crowdLevel: 'high', safetyScore: 90, isSoloVerified: true, transitNoteBefore: 'A 4-min walk south across the park from Hagia Sophia.', insiderTip: 'Use the Hippodrome-side entrance rather than the seaward tourist queue — it moves far faster. Shoes come off, so wear socks you do not mind walking in.', photoGoldenHour: 'Blue hour after sunset, when all six minarets are floodlit — shoot from Sultanahmet Park.', priceTier: 1, emoji: '🕌', source: 'IBB Open Data' },
  { placeId: 'ChIJ-sultanahmet-topkapi', name: 'Topkapı Palace', hub: 'sultanahmet', lat: 41.0115, lng: 28.9834, rating: 4.7, reviewCount: 156900, photoUrl: 'https://images.pathwise.mock/topkapi.jpg', category: 'history', interests: ['history', 'photo'], entryFeeTry: 1700, avgFoodCostTry: 0, avgVisitMinutes: 120, openingHours: 'Wed–Mon 09:00–18:00 (closed Tue)', isIndoor: true, isSunsetSpot: false, museumPass: true, localTip: 'The Harem needs a separate ticket but is the highlight — buy it.', neighborhood: 'Sultanahmet', crowdLevel: 'high', safetyScore: 90, isSoloVerified: true, transitNoteBefore: 'A 6-min walk from Hagia Sophia through the Imperial Gate.', insiderTip: 'The Harem is a separate ticket bought at its own gate — do it first while the queue is short, then loop back through the four courtyards.', photoGoldenHour: 'Late afternoon from the Fourth Courtyard terrace, looking down the Bosphorus.', priceTier: 3, emoji: '🏰', source: 'Google Places' },
  { placeId: 'ChIJ-sultanahmet-basilicacistern', name: 'Basilica Cistern (Yerebatan Sarnıcı)', hub: 'sultanahmet', lat: 41.0084, lng: 28.9779, rating: 4.6, reviewCount: 142300, photoUrl: 'https://images.pathwise.mock/yerebatan.jpg', category: 'history', interests: ['history', 'photo'], entryFeeTry: 900, avgFoodCostTry: 0, avgVisitMinutes: 40, openingHours: 'Daily 09:00–22:00', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'Great rainy-day stop — fully underground and atmospheric.', neighborhood: 'Sultanahmet', crowdLevel: 'high', safetyScore: 89, isSoloVerified: true, transitNoteBefore: 'A 2-min walk from the Hagia Sophia tram stop, entrance on Yerebatan Cd.', insiderTip: 'The two Medusa-head column bases are tucked in the far back corner — walk the whole loop or you will miss them. Late timed-entry slots are the emptiest.', photoGoldenHour: 'Indoors year-round; the uplit columns read best from the raised walkway.', priceTier: 2, emoji: '🏛️', source: 'Google Places' },
  { placeId: 'ChIJ-sultanahmet-grandbazaar', name: 'Grand Bazaar (Kapalıçarşı)', hub: 'sultanahmet', lat: 41.0106, lng: 28.968, rating: 4.5, reviewCount: 220110, photoUrl: 'https://images.pathwise.mock/grand-bazaar.jpg', category: 'market', interests: ['market', 'photo'], entryFeeTry: 0, avgFoodCostTry: 180, avgVisitMinutes: 60, openingHours: 'Mon–Sat 09:00–19:00 (closed Sun)', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'Prices drop 30–40% if you walk away once — haggling is expected.', neighborhood: 'Beyazıt', crowdLevel: 'high', safetyScore: 84, isSoloVerified: true, transitNoteBefore: 'T1 tram to Beyazıt-Kapalıçarşı, then straight into the Nuruosmaniye gate.', insiderTip: 'The İç Bedesten at the very centre is the oldest hall and where the real antiques and silver are; the perimeter lanes are tourist-priced. Closed all day Sunday.', photoGoldenHour: 'Mid-morning, when light drops through the painted vaults onto the main Kalpakçılar lane.', priceTier: 2, emoji: '🛒', source: 'Google Places' },
  { placeId: 'ChIJ-sultanahmet-gulhane', name: 'Gülhane Park', hub: 'sultanahmet', lat: 41.0134, lng: 28.9812, rating: 4.6, reviewCount: 63400, photoUrl: 'https://images.pathwise.mock/gulhane.jpg', category: 'nature', interests: ['nature', 'photo'], entryFeeTry: 0, avgFoodCostTry: 120, avgVisitMinutes: 45, openingHours: 'Daily 06:00–22:30', isIndoor: false, isSunsetSpot: true, museumPass: false, localTip: 'The far terrace has a free Bosphorus view most tourists miss.', neighborhood: 'Sultanahmet', crowdLevel: 'medium', safetyScore: 88, isSoloVerified: true, transitNoteBefore: 'T1 tram to Gülhane, the gate is right at the stop.', insiderTip: 'In April the park is the tulip carpet the city is famous for. Any other month, the rose garden by the Alay Köşkü gate is the quiet corner nobody walks to.', photoGoldenHour: 'Morning, with the plane trees backlit down the main avenue.', priceTier: 1, emoji: '🌳', source: 'IBB Open Data' },
  { placeId: 'ChIJ-sultanahmet-kucukayasofya', name: 'Little Hagia Sophia (Küçük Ayasofya)', hub: 'sultanahmet', lat: 41.0027, lng: 28.9719, rating: 4.7, reviewCount: 9800, photoUrl: 'https://images.pathwise.mock/kucuk-ayasofya.jpg', category: 'history', interests: ['history', 'photo'], entryFeeTry: 0, avgFoodCostTry: 0, avgVisitMinutes: 30, openingHours: 'Daily, outside prayer times', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'A 6th-century Byzantine church turned mosque; read the carved Greek frieze naming Justinian.', neighborhood: 'Sultanahmet', crowdLevel: 'low', safetyScore: 92, isSoloVerified: true, transitNoteBefore: 'Quiet 8-min downhill walk from the Blue Mosque toward the Marmara shore.', insiderTip: 'The shaded courtyard tea garden is free and almost always empty — the calmest çay two blocks from the tourist crush.', photoGoldenHour: 'Late afternoon; western sun rakes across the columned portico and green courtyard.', priceTier: 1, emoji: '🕌', source: 'Google Places' },
  { placeId: 'ChIJ-sultanahmet-turkislam', name: 'Museum of Turkish & Islamic Arts', hub: 'sultanahmet', lat: 41.0061, lng: 28.9748, rating: 4.6, reviewCount: 21600, photoUrl: 'https://images.pathwise.mock/turk-islam.jpg', category: 'art', interests: ['art', 'history'], entryFeeTry: 700, avgFoodCostTry: 0, avgVisitMinutes: 70, openingHours: 'Tue–Sun 09:00–18:30 (closed Mon)', isIndoor: true, isSunsetSpot: false, museumPass: true, localTip: 'Housed in İbrahim Paşa Palace on the Hippodrome; the antique carpet collection is world-class.', neighborhood: 'Sultanahmet', crowdLevel: 'low', safetyScore: 91, isSoloVerified: true, transitNoteBefore: 'Facing the Hippodrome, a 2-min walk from the Blue Mosque’s west side.', insiderTip: 'A perfect rainy-day pairing with the Cistern — it is indoors and rarely queued even in peak season.', photoGoldenHour: 'Shoot the palace loggia and Obelisk together from the terrace before midday glare.', priceTier: 2, emoji: '🖼️', source: 'IBB Open Data' },
  { placeId: 'ChIJ-sultanahmet-hippodrome', name: 'Hippodrome (Sultanahmet Meydanı)', hub: 'sultanahmet', lat: 41.0056, lng: 28.9754, rating: 4.6, reviewCount: 71200, photoUrl: 'https://images.pathwise.mock/hippodrome.jpg', category: 'history', interests: ['history', 'photo'], entryFeeTry: 0, avgFoodCostTry: 0, avgVisitMinutes: 30, openingHours: 'Always open', isIndoor: false, isSunsetSpot: false, museumPass: false, localTip: 'The Egyptian Obelisk, Serpent Column and German Fountain line the old Byzantine chariot track.', neighborhood: 'Sultanahmet', crowdLevel: 'high', safetyScore: 90, isSoloVerified: true, transitNoteBefore: 'Directly between the Blue Mosque and the Arts Museum — no transit needed.', insiderTip: 'Come before 09:00 to photograph the 3,500-year-old Obelisk with no crowds and soft light on the hieroglyphs.', photoGoldenHour: 'Early morning, sun behind you lighting the Obelisk’s east face and the Blue Mosque domes.', priceTier: 1, emoji: '🏛️', source: 'Google Places' },
  { placeId: 'ChIJ-sultanahmet-spicebazaar', name: 'Spice Bazaar (Mısır Çarşısı)', hub: 'sultanahmet', lat: 41.0165, lng: 28.9707, rating: 4.5, reviewCount: 168400, photoUrl: 'https://images.pathwise.mock/spice-bazaar.jpg', category: 'market', interests: ['market', 'food', 'photo'], entryFeeTry: 0, avgFoodCostTry: 200, avgVisitMinutes: 45, openingHours: 'Daily 09:00–19:00', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'Buy saffron, Iranian pistachios and Turkish delight; taste before you commit.', neighborhood: 'Eminönü', crowdLevel: 'high', safetyScore: 84, isSoloVerified: true, transitNoteBefore: 'T1 tram to Eminönü, then a 3-min walk past the New Mosque courtyard.', insiderTip: 'The best-value shops are the ones outside the L-shaped hall, on Hasırcılar Cd. — locals buy their spices there for half the price.', photoGoldenHour: 'Mid-morning when shafts of light hit the pyramids of coloured spice at the arched entrances.', priceTier: 2, emoji: '🌶️', source: 'Google Places' },
  { placeId: 'ChIJ-sultanahmet-koftecisi', name: 'Tarihi Sultanahmet Köftecisi', hub: 'sultanahmet', lat: 41.0086, lng: 28.9762, rating: 4.3, reviewCount: 44800, photoUrl: 'https://images.pathwise.mock/sultanahmet-koftecisi.jpg', category: 'food', interests: ['food'], entryFeeTry: 0, avgFoodCostTry: 260, avgVisitMinutes: 40, openingHours: 'Daily 11:00–23:00', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'A 1920 grilled-köfte institution; the menu is basically köfte, piyaz and ayran.', neighborhood: 'Sultanahmet', crowdLevel: 'medium', safetyScore: 88, isSoloVerified: true, transitNoteBefore: 'On Divanyolu, a 4-min walk from the Basilica Cistern beside the tram line.', insiderTip: 'Ignore the copycats with similar names nearby — the original is the one at Divanyolu No. 12A with the queue of locals.', photoGoldenHour: 'No view spot — this is a quick, honest lunch between monuments.', priceTier: 2, emoji: '🍢', source: 'Google Places' },

  // ── Karaköy & Galata ──
  { placeId: 'ChIJ-galata-tower', name: 'Galata Tower', hub: 'karakoy-galata', lat: 41.0256, lng: 28.9744, rating: 4.6, reviewCount: 178500, photoUrl: 'https://images.pathwise.mock/galata-tower.jpg', category: 'history', interests: ['history', 'photo'], entryFeeTry: 1000, avgFoodCostTry: 0, avgVisitMinutes: 50, openingHours: 'Daily 08:30–23:00', isIndoor: true, isSunsetSpot: true, museumPass: true, localTip: 'Go 45 min before sunset for golden-hour light over the Horn.', neighborhood: 'Galata', crowdLevel: 'high', safetyScore: 88, isSoloVerified: true, transitNoteBefore: 'Tünel funicular from Karaköy, then a 4-min walk down Galip Dede Cd.', insiderTip: 'The queue peaks exactly 45 minutes before sunset — the moment you want to be at the top. Book the timed online ticket, or come at opening and accept flatter light.', photoGoldenHour: 'Shoot the tower itself from Büyük Hendek Cd. at dusk; from the top, sunset over the Golden Horn.', priceTier: 3, emoji: '🗼', source: 'Google Places' },
  { placeId: 'ChIJ-galata-karakoylokantasi', name: 'Karaköy Lokantası', hub: 'karakoy-galata', lat: 41.0242, lng: 28.9776, rating: 4.6, reviewCount: 21400, photoUrl: 'https://images.pathwise.mock/karakoy-lokantasi.jpg', category: 'food', interests: ['food'], entryFeeTry: 0, avgFoodCostTry: 650, avgVisitMinutes: 75, openingHours: 'Mon–Sat 12:00–16:00, 19:00–23:00', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'The turquoise-tiled meyhane; book ahead for dinner, walk-in at lunch.', neighborhood: 'Karaköy', crowdLevel: 'medium', safetyScore: 88, isSoloVerified: true, transitNoteBefore: 'A 3-min walk from Karaköy pier, just behind the Kemankeş Cd. corner.', insiderTip: 'It runs as two different places: a quick tiled-room lunch canteen, and a full meyhane at night. Walk in at noon; book ahead for dinner.', photoGoldenHour: 'Interior — the turquoise tilework reads best in daylight at lunch.', priceTier: 3, emoji: '🍽️', source: 'Google Places' },
  { placeId: 'ChIJ-galata-saltgalata', name: 'SALT Galata', hub: 'karakoy-galata', lat: 41.0231, lng: 28.9741, rating: 4.5, reviewCount: 9800, photoUrl: 'https://images.pathwise.mock/salt-galata.jpg', category: 'art', interests: ['art', 'history'], entryFeeTry: 0, avgFoodCostTry: 220, avgVisitMinutes: 60, openingHours: 'Tue–Sun 10:00–18:00 (closed Mon)', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'Free contemporary art space in the old Ottoman Bank — great café.', neighborhood: 'Karaköy', crowdLevel: 'low', safetyScore: 90, isSoloVerified: true, transitNoteBefore: 'A 4-min walk uphill from Karaköy pier along Bankalar Cd.', insiderTip: 'The old Ottoman Bank vault in the basement is a free museum, and the top-floor reading room is open to anyone who walks in — no ticket, no membership.', photoGoldenHour: 'Interior; the banking hall under its skylight around midday.', priceTier: 1, emoji: '🏛️', source: 'Google Places' },
  { placeId: 'ChIJ-galata-gulluoglu', name: 'Karaköy Güllüoğlu', hub: 'karakoy-galata', lat: 41.0231, lng: 28.9781, rating: 4.6, reviewCount: 44200, photoUrl: 'https://images.pathwise.mock/gulluoglu.jpg', category: 'food', interests: ['food'], entryFeeTry: 0, avgFoodCostTry: 160, avgVisitMinutes: 30, openingHours: 'Daily 07:00–22:00', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'Order the pistachio baklava by weight; pay the cashier first.', neighborhood: 'Karaköy', crowdLevel: 'high', safetyScore: 88, isSoloVerified: true, transitNoteBefore: 'Directly beside Karaköy ferry pier, under the elevated road.', insiderTip: 'Ask for it "az şerbetli" (less syrup) if Turkish sweets are usually too much for you — they will cut a fresh piece from the tray rather than hand you a pre-soaked one.', photoGoldenHour: 'No view — this is a 20-minute standing-counter stop.', priceTier: 2, emoji: '🍮', source: 'Google Places' },
  { placeId: 'ChIJ-galata-camondo', name: 'Camondo Steps', hub: 'karakoy-galata', lat: 41.0243, lng: 28.9737, rating: 4.4, reviewCount: 15600, photoUrl: 'https://images.pathwise.mock/camondo.jpg', category: 'photo', interests: ['photo', 'history'], entryFeeTry: 0, avgFoodCostTry: 0, avgVisitMinutes: 20, openingHours: 'Always open', isIndoor: false, isSunsetSpot: false, museumPass: false, localTip: 'Shoot from the bottom looking up for the famous Art Nouveau curve.', neighborhood: 'Karaköy', crowdLevel: 'medium', safetyScore: 86, isSoloVerified: true, transitNoteBefore: 'On Bankalar Cd., a 2-min walk up from SALT Galata.', insiderTip: 'Built by the Camondo banking family in the 1870s as a shortcut up to the Galata banks. Come before 10:00 — by midday it is a rotation of photo shoots.', photoGoldenHour: 'Morning, when the east-facing double curve is lit and still empty.', priceTier: 1, emoji: '📸', source: 'Google Places' },
  { placeId: 'ChIJ-galata-istanbulmodern', name: 'Istanbul Modern', hub: 'karakoy-galata', lat: 41.0247, lng: 28.9799, rating: 4.6, reviewCount: 38700, photoUrl: 'https://images.pathwise.mock/istanbul-modern.jpg', category: 'art', interests: ['art', 'photo'], entryFeeTry: 650, avgFoodCostTry: 220, avgVisitMinutes: 80, openingHours: 'Tue–Sun 10:00–18:00 (closed Mon)', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'Renzo Piano’s waterfront building on Galataport; the mirrored roof pool is a landmark.', neighborhood: 'Karaköy', crowdLevel: 'medium', safetyScore: 90, isSoloVerified: true, transitNoteBefore: 'A 6-min shoreline walk from Karaköy pier along the Galataport promenade.', insiderTip: 'The top-floor terrace café is free to enter without a ticket and frames the Old City skyline across the Horn.', photoGoldenHour: 'Sunset, when the reflecting pool on the roof mirrors the Süleymaniye silhouette.', priceTier: 3, emoji: '🖼️', source: 'Google Places' },
  { placeId: 'ChIJ-galata-mevlevihane', name: 'Galata Mevlevi Lodge Museum', hub: 'karakoy-galata', lat: 41.0295, lng: 28.9748, rating: 4.5, reviewCount: 11200, photoUrl: 'https://images.pathwise.mock/mevlevihane.jpg', category: 'history', interests: ['history', 'art'], entryFeeTry: 300, avgFoodCostTry: 0, avgVisitMinutes: 45, openingHours: 'Tue–Sun 09:00–16:30 (closed Mon)', isIndoor: true, isSunsetSpot: false, museumPass: true, localTip: 'A 15th-century whirling-dervish lodge; the octagonal semahane hall hosts real sema ceremonies.', neighborhood: 'Galata', crowdLevel: 'low', safetyScore: 89, isSoloVerified: true, transitNoteBefore: 'Top of the İstiklal end of Galip Dede Cd., a 5-min walk up from Galata Tower.', insiderTip: 'Sema ceremonies run some Sunday evenings — buy the separate performance ticket a day ahead, it sells out.', photoGoldenHour: 'Interior only; soft morning light through the lattice windows onto the wooden floor.', priceTier: 1, emoji: '🌀', source: 'IBB Open Data' },
  { placeId: 'ChIJ-galata-kilicalipasa', name: 'Kılıç Ali Paşa Mosque & Hamam', hub: 'karakoy-galata', lat: 41.0238, lng: 28.9805, rating: 4.7, reviewCount: 8400, photoUrl: 'https://images.pathwise.mock/kilic-ali-pasa.jpg', category: 'history', interests: ['history', 'photo'], entryFeeTry: 0, avgFoodCostTry: 0, avgVisitMinutes: 35, openingHours: 'Mosque: outside prayer times; Hamam: daily 08:00–22:00', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'A 1580 Sinan mosque; the adjoining restored hamam is one of the city’s finest.', neighborhood: 'Tophane', crowdLevel: 'low', safetyScore: 88, isSoloVerified: true, transitNoteBefore: 'A 5-min walk east from Karaköy along Kemeraltı Cd. toward Tophane.', insiderTip: 'The hamam runs separate men’s and women’s hours, not mixed — check the daily schedule before you go rather than turning up.', photoGoldenHour: 'Late afternoon light on the courtyard fountain and lead-domed roofline.', priceTier: 1, emoji: '🕌', source: 'Google Places' },
  { placeId: 'ChIJ-galata-namli', name: 'Namlı Gurme (Karaköy)', hub: 'karakoy-galata', lat: 41.0227, lng: 28.9772, rating: 4.5, reviewCount: 29300, photoUrl: 'https://images.pathwise.mock/namli-gurme.jpg', category: 'food', interests: ['food'], entryFeeTry: 0, avgFoodCostTry: 420, avgVisitMinutes: 60, openingHours: 'Daily 06:00–21:00', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'A sprawling deli famous for its serpme kahvaltı (spread breakfast) under the Galataport arches.', neighborhood: 'Karaköy', crowdLevel: 'high', safetyScore: 87, isSoloVerified: true, transitNoteBefore: 'Right beside Karaköy ferry pier under the elevated road — 1 min from the boats.', insiderTip: 'Weekends are mobbed; go on a weekday morning and order the cheese-counter breakfast plate rather than the fixed spread if you’re solo.', photoGoldenHour: 'No view — this is a breakfast-and-deli stop, best mid-morning.', priceTier: 3, emoji: '🧀', source: 'Google Places' },

  // ── Kadıköy & Moda ──
  { placeId: 'ChIJ-kadikoy-carsi', name: 'Kadıköy Market (Çarşı)', hub: 'kadikoy-moda', lat: 40.9903, lng: 29.0277, rating: 4.7, reviewCount: 58900, photoUrl: 'https://images.pathwise.mock/kadikoy-carsi.jpg', category: 'market', interests: ['market', 'food', 'photo'], entryFeeTry: 0, avgFoodCostTry: 250, avgVisitMinutes: 60, openingHours: 'Daily 08:00–20:00', isIndoor: false, isSunsetSpot: false, museumPass: false, localTip: 'Graze: pickles at Şükrü, Turkish delight at Hacı Bekir, fish sandwiches.', neighborhood: 'Kadıköy', crowdLevel: 'high', safetyScore: 88, isSoloVerified: true, transitNoteBefore: 'A 3-min walk inland from Kadıköy ferry pier.', insiderTip: 'Tuesday to Saturday is full swing; on Sunday half the stalls shut. Start at the fish market end and work inland — the produce and pickle shops are deeper in.', photoGoldenHour: 'Late morning, when the fish and produce are freshly iced and stacked.', priceTier: 2, emoji: '🐟', source: 'Google Places' },
  { placeId: 'ChIJ-kadikoy-ciya', name: 'Çiya Sofrası', hub: 'kadikoy-moda', lat: 40.9899, lng: 29.0271, rating: 4.6, reviewCount: 33100, photoUrl: 'https://images.pathwise.mock/ciya.jpg', category: 'food', interests: ['food'], entryFeeTry: 0, avgFoodCostTry: 420, avgVisitMinutes: 70, openingHours: 'Daily 11:00–22:00', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'Point-and-pick Anatolian dishes; the tatlı is unique.', neighborhood: 'Kadıköy', crowdLevel: 'high', safetyScore: 89, isSoloVerified: true, transitNoteBefore: 'In the market lanes on Güneşlibahçe Sk., a 5-min walk from the pier.', insiderTip: 'Point at what you want from the counter trays instead of ordering off the menu — the regional Anatolian dishes rotate daily and the counter is the real menu.', photoGoldenHour: 'No view; go at lunch when the widest spread is out.', priceTier: 2, emoji: '🍲', source: 'Google Places' },
  { placeId: 'ChIJ-kadikoy-moda-sahil', name: 'Moda Seaside (Sahil)', hub: 'kadikoy-moda', lat: 40.9812, lng: 29.024, rating: 4.7, reviewCount: 41200, photoUrl: 'https://images.pathwise.mock/moda-sahil.jpg', category: 'nature', interests: ['nature', 'photo'], entryFeeTry: 0, avgFoodCostTry: 90, avgVisitMinutes: 50, openingHours: 'Always open', isIndoor: false, isSunsetSpot: true, museumPass: false, localTip: 'Grab a çay and watch the sun set behind the peninsula.', neighborhood: 'Moda', crowdLevel: 'medium', safetyScore: 90, isSoloVerified: true, transitNoteBefore: 'A 12-min walk south from Kadıköy along the shoreline path.', insiderTip: 'The grass terraces fill with locals and roaming tea sellers at sunset. Bring a blanket and buy çay from the trolley rather than hunting for a café table.', photoGoldenHour: 'Sunset over the historic peninsula, straight off the seawall.', priceTier: 1, emoji: '🌊', source: 'IBB Open Data' },
  { placeId: 'ChIJ-kadikoy-moda-icecream', name: 'Moda Dondurma (Ali Usta)', hub: 'kadikoy-moda', lat: 40.9836, lng: 29.0263, rating: 4.5, reviewCount: 27600, photoUrl: 'https://images.pathwise.mock/ali-usta.jpg', category: 'food', interests: ['food'], entryFeeTry: 0, avgFoodCostTry: 110, avgVisitMinutes: 20, openingHours: 'Daily 10:00–00:00', isIndoor: false, isSunsetSpot: false, museumPass: false, localTip: 'Expect a queue in summer; the sakızlı scoop is the local pick.', neighborhood: 'Moda', crowdLevel: 'high', safetyScore: 89, isSoloVerified: true, transitNoteBefore: 'On Moda Cd., a 2-min walk from the Moda seaside path.', insiderTip: 'Take the cone down to the seaside two blocks away rather than queueing for a table — that is exactly what the neighbourhood does.', photoGoldenHour: 'No view; the shopfront is liveliest after dark in summer.', priceTier: 1, emoji: '🍦', source: 'Google Places' },
  { placeId: 'ChIJ-kadikoy-barlar', name: 'Kadıköy Barlar Sokağı', hub: 'kadikoy-moda', lat: 40.9895, lng: 29.0292, rating: 4.4, reviewCount: 18400, photoUrl: 'https://images.pathwise.mock/barlar-sokagi.jpg', category: 'food', interests: ['food', 'art'], entryFeeTry: 0, avgFoodCostTry: 380, avgVisitMinutes: 60, openingHours: 'Daily 16:00–02:00', isIndoor: false, isSunsetSpot: false, museumPass: false, localTip: 'Best after dark; live music spills out of the side streets on weekends.', neighborhood: 'Kadıköy', crowdLevel: 'high', safetyScore: 82, isSoloVerified: true, transitNoteBefore: 'A 5-min walk from the pier, behind the Kadıköy market lanes.', insiderTip: 'Kadife Sk. is the famous spine, but the cheaper, quieter bars are one street over on Dumlupınar — same crowd, half the queue.', photoGoldenHour: 'After dark, when the string lights come on and the crowd spills into the street.', priceTier: 3, emoji: '🍻', source: 'Google Places' },
  { placeId: 'ChIJ-kadikoy-sureyya', name: 'Süreyya Opera House', hub: 'kadikoy-moda', lat: 40.9906, lng: 29.0286, rating: 4.6, reviewCount: 8700, photoUrl: 'https://images.pathwise.mock/sureyya.jpg', category: 'art', interests: ['art', 'history', 'photo'], entryFeeTry: 0, avgFoodCostTry: 0, avgVisitMinutes: 30, openingHours: 'Lobby daily; performances evenings', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'The 1927 façade on Bahariye is a photo stop even without a show.', neighborhood: 'Kadıköy', crowdLevel: 'low', safetyScore: 90, isSoloVerified: true, transitNoteBefore: 'On Bahariye Cd., a 6-min walk up from the ferry pier.', insiderTip: 'The lobby is open in the daytime and free to step into — the 1927 interior was modelled on Parisian opera houses and almost nobody walks in to look.', photoGoldenHour: 'Evening, when the Bahariye façade is lit and the nostalgic tram rattles past.', priceTier: 1, emoji: '🎭', source: 'IBB Open Data' },
  { placeId: 'ChIJ-kadikoy-bahariye', name: 'Bahariye Caddesi', hub: 'kadikoy-moda', lat: 40.9902, lng: 29.0289, rating: 4.4, reviewCount: 22100, photoUrl: 'https://images.pathwise.mock/bahariye.jpg', category: 'market', interests: ['market', 'photo'], entryFeeTry: 0, avgFoodCostTry: 150, avgVisitMinutes: 45, openingHours: 'Shops daily 10:00–22:00', isIndoor: false, isSunsetSpot: false, museumPass: false, localTip: 'Kadıköy’s pedestrian shopping spine, from the bull statue to Süreyya Opera.', neighborhood: 'Kadıköy', crowdLevel: 'high', safetyScore: 86, isSoloVerified: true, transitNoteBefore: 'A 4-min walk up from Kadıköy ferry pier past the famous Boğa (bull) statue.', insiderTip: 'Duck into the side arcade Akmar Pasajı for second-hand vinyl, comics and band tees — it’s the counterculture heart locals grew up in.', photoGoldenHour: 'Evening, when the nostalgic tram rattles down the lit street.', priceTier: 2, emoji: '🛍️', source: 'Google Places' },
  { placeId: 'ChIJ-kadikoy-modapier', name: 'Moda Pier (Moda İskelesi)', hub: 'kadikoy-moda', lat: 40.9789, lng: 29.0268, rating: 4.6, reviewCount: 33900, photoUrl: 'https://images.pathwise.mock/moda-iskelesi.jpg', category: 'photo', interests: ['photo', 'nature'], entryFeeTry: 0, avgFoodCostTry: 130, avgVisitMinutes: 40, openingHours: 'Café daily 08:00–23:00', isIndoor: false, isSunsetSpot: true, museumPass: false, localTip: 'A 1917 Art Nouveau ferry pavilion, now a café jutting into the sea.', neighborhood: 'Moda', crowdLevel: 'medium', safetyScore: 90, isSoloVerified: true, transitNoteBefore: 'A pleasant 15-min shoreline walk from Kadıköy along the Moda seaside path.', insiderTip: 'Walk to the very end of the pier deck for a 270° water view — it frames the Old City domes and the islands on a clear day.', photoGoldenHour: 'Sunset behind the historic peninsula, straight off the pier’s western rail.', priceTier: 2, emoji: '⚓', source: 'Google Places' },
  { placeId: 'ChIJ-kadikoy-yeldegirmeni', name: 'Yeldeğirmeni Murals', hub: 'kadikoy-moda', lat: 40.9962, lng: 29.0258, rating: 4.5, reviewCount: 12700, photoUrl: 'https://images.pathwise.mock/yeldegirmeni.jpg', category: 'art', interests: ['art', 'photo'], entryFeeTry: 0, avgFoodCostTry: 120, avgVisitMinutes: 45, openingHours: 'Always open', isIndoor: false, isSunsetSpot: false, museumPass: false, localTip: 'A historic railway-worker district reborn as an open-air street-art gallery.', neighborhood: 'Yeldeğirmeni', crowdLevel: 'low', safetyScore: 85, isSoloVerified: true, transitNoteBefore: 'A 6-min walk inland from Kadıköy toward the Marmaray, or one Marmaray stop to Ayrılık Çeşmesi.', insiderTip: 'The biggest murals cluster on Karakolhane and Macit Erbudak streets — follow the “Mural Istanbul” festival works building by building.', photoGoldenHour: 'Overcast light is best for shooting murals flat and colour-true, no harsh shadows.', priceTier: 1, emoji: '🎨', source: 'Google Places' },
  { placeId: 'ChIJ-kadikoy-baylan', name: 'Baylan Pastanesi', hub: 'kadikoy-moda', lat: 40.9905, lng: 29.0282, rating: 4.5, reviewCount: 15900, photoUrl: 'https://images.pathwise.mock/baylan.jpg', category: 'food', interests: ['food', 'history'], entryFeeTry: 0, avgFoodCostTry: 240, avgVisitMinutes: 40, openingHours: 'Daily 08:00–23:00', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'A 1961 patisserie; the “Kup Griye” caramel-praline sundae is its signature.', neighborhood: 'Kadıköy', crowdLevel: 'medium', safetyScore: 89, isSoloVerified: true, transitNoteBefore: 'Just off Muvakkithane Cd., a 3-min walk from the pier through the market.', insiderTip: 'Sit in the leafy back garden, not the front room, and order the Kup Griye — the recipe hasn’t changed in 60 years.', photoGoldenHour: 'No view; the retro garden is prettiest in dappled afternoon light.', priceTier: 2, emoji: '🍨', source: 'Google Places' },

  // ── Balat & Fener ──
  { placeId: 'ChIJ-balat-colorfulhouses', name: 'Balat Colorful Houses (Kiremit Cd.)', hub: 'balat-fener', lat: 41.0294, lng: 28.9487, rating: 4.6, reviewCount: 52300, photoUrl: 'https://images.pathwise.mock/balat-houses.jpg', category: 'photo', interests: ['photo', 'history'], entryFeeTry: 0, avgFoodCostTry: 0, avgVisitMinutes: 45, openingHours: 'Always open', isIndoor: false, isSunsetSpot: false, museumPass: false, localTip: 'Kiremit & Merdivenli Yokuş have the rainbow terraces — mornings are quietest.', neighborhood: 'Balat', crowdLevel: 'high', safetyScore: 84, isSoloVerified: true, transitNoteBefore: 'Bus or ferry to Fener/Balat, then a 5-min walk up Kiremit Cd.', insiderTip: 'These are private homes with people living behind the doors — shoot from the street and keep your voice down. Skip the "rent a dress for photos" stalls that have taken over Merdivenli Yokuş.', photoGoldenHour: 'Early morning; by 11:00 the lanes are a queue of photo shoots.', priceTier: 1, emoji: '🌈', source: 'Google Places' },
  { placeId: 'ChIJ-balat-fenerpatriarchate', name: 'Ecumenical Patriarchate (Fener)', hub: 'balat-fener', lat: 41.0293, lng: 28.9513, rating: 4.6, reviewCount: 12100, photoUrl: 'https://images.pathwise.mock/patriarchate.jpg', category: 'history', interests: ['history'], entryFeeTry: 0, avgFoodCostTry: 0, avgVisitMinutes: 35, openingHours: 'Daily 09:00–17:00', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'The seat of the Greek Orthodox church; modest dress appreciated.', neighborhood: 'Fener', crowdLevel: 'low', safetyScore: 87, isSoloVerified: true, transitNoteBefore: 'A 7-min walk along the Golden Horn shore road from Balat.', insiderTip: 'The seat of the Orthodox world since 1601. St George’s Church inside holds the patriarchal throne; dress modestly and expect a bag check at the gate.', photoGoldenHour: 'Morning — the courtyard is small and falls into shade by afternoon.', priceTier: 1, emoji: '⛪', source: 'Google Places' },
  { placeId: 'ChIJ-balat-agora', name: 'Agora Meyhanesi 1890', hub: 'balat-fener', lat: 41.0286, lng: 28.9497, rating: 4.5, reviewCount: 9600, photoUrl: 'https://images.pathwise.mock/agora-meyhanesi.jpg', category: 'food', interests: ['food'], entryFeeTry: 0, avgFoodCostTry: 550, avgVisitMinutes: 80, openingHours: 'Daily 12:00–00:00', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'A 130-year-old meyhane; order the meze board and rakı like a local.', neighborhood: 'Balat', crowdLevel: 'medium', safetyScore: 86, isSoloVerified: true, transitNoteBefore: 'A 4-min walk from the Balat colourful houses toward the shore.', insiderTip: 'Order meze by pointing at the tray the waiter carries to your table, then one hot dish to share — that is the meyhane rhythm, not a starter-then-main sequence.', photoGoldenHour: 'Interior; the old Greek-tavern room is warmest after dark.', priceTier: 3, emoji: '🍷', source: 'Google Places' },
  { placeId: 'ChIJ-balat-antiqueshops', name: 'Balat Antique & Vintage Shops', hub: 'balat-fener', lat: 41.0301, lng: 28.9479, rating: 4.4, reviewCount: 6400, photoUrl: 'https://images.pathwise.mock/balat-antiques.jpg', category: 'market', interests: ['market', 'art', 'photo'], entryFeeTry: 0, avgFoodCostTry: 0, avgVisitMinutes: 40, openingHours: 'Tue–Sun 10:00–19:00', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'Perfect rainy detour; the antikacı shops around Vodina Cd. are treasure troves.', neighborhood: 'Balat', crowdLevel: 'low', safetyScore: 84, isSoloVerified: true, transitNoteBefore: 'Clustered on Lapçinler and Yıldırım Cd., a 3-min walk from Kiremit Cd.', insiderTip: 'Most shops open late morning and shut early, and many close on Sunday — go midday on a weekday or you will find shutters down.', photoGoldenHour: 'Late morning, when shopkeepers set their pieces out across the pavement.', priceTier: 2, emoji: '🕰️', source: 'Google Places' },
  { placeId: 'ChIJ-balat-cafe', name: 'Forno Balat (Café)', hub: 'balat-fener', lat: 41.029, lng: 28.9482, rating: 4.5, reviewCount: 14300, photoUrl: 'https://images.pathwise.mock/forno-balat.jpg', category: 'food', interests: ['food', 'photo'], entryFeeTry: 0, avgFoodCostTry: 240, avgVisitMinutes: 45, openingHours: 'Daily 08:00–20:00', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'Old stone bakery-café; the simit-and-menemen breakfast is the move.', neighborhood: 'Balat', crowdLevel: 'medium', safetyScore: 85, isSoloVerified: true, transitNoteBefore: 'On the corner of Vodina Cd., a 3-min walk from the colourful houses.', insiderTip: 'A wood-fired bakery best known for pide and lahmacun rather than coffee — and the small upstairs room is far quieter than the photographed street tables.', photoGoldenHour: 'The blue-shuttered corner façade shoots well in late-morning light.', priceTier: 2, emoji: '🥖', source: 'Google Places' },

  // ── Beşiktaş & Bosphorus ──
  { placeId: 'ChIJ-besiktas-dolmabahce', name: 'Dolmabahçe Palace', hub: 'besiktas-bogaz', lat: 41.0392, lng: 29.0001, rating: 4.7, reviewCount: 121700, photoUrl: 'https://images.pathwise.mock/dolmabahce.jpg', category: 'history', interests: ['history', 'photo'], entryFeeTry: 1450, avgFoodCostTry: 0, avgVisitMinutes: 90, openingHours: 'Tue–Sun 09:00–16:00 (closed Mon)', isIndoor: true, isSunsetSpot: false, museumPass: false, localTip: 'Photography is limited inside; the waterfront clock tower is the free shot.', neighborhood: 'Beşiktaş', crowdLevel: 'high', safetyScore: 90, isSoloVerified: true, transitNoteBefore: 'A 10-min shoreline walk from Beşiktaş pier, or the T1 tram to Kabataş.', insiderTip: 'You can only go inside on a guided tour, and the Selamlık and Harem are separate tickets. The last tour leaves well before closing time — arrive by mid-afternoon at the latest.', photoGoldenHour: 'Afternoon from the Bosphorus-facing gates, or from the deck of any passing ferry.', priceTier: 3, emoji: '🏛️', source: 'IBB Open Data' },
  { placeId: 'ChIJ-besiktas-ortakoy-mosque', name: 'Ortaköy Mosque', hub: 'besiktas-bogaz', lat: 41.0473, lng: 29.0272, rating: 4.7, reviewCount: 88100, photoUrl: 'https://images.pathwise.mock/ortakoy.jpg', category: 'photo', interests: ['photo', 'history'], entryFeeTry: 0, avgFoodCostTry: 0, avgVisitMinutes: 40, openingHours: 'Daily, outside prayer times', isIndoor: false, isSunsetSpot: true, museumPass: false, localTip: 'Frame the mosque with the Bosphorus Bridge behind it from the square.', neighborhood: 'Ortaköy', crowdLevel: 'high', safetyScore: 87, isSoloVerified: true, transitNoteBefore: 'Bus along the shore road from Beşiktaş, about 10 min.', insiderTip: 'The postcard shot lines the mosque up with the Bosphorus Bridge behind it — stand on the small pier to the left of the mosque, not in the crowded square.', photoGoldenHour: 'Sunset into blue hour, when the mosque and the bridge are both lit.', priceTier: 1, emoji: '🕌', source: 'Google Places' },
  { placeId: 'ChIJ-besiktas-ortakoy-kumpir', name: 'Ortaköy Kumpir & Waffle Row', hub: 'besiktas-bogaz', lat: 41.0476, lng: 29.0266, rating: 4.4, reviewCount: 36700, photoUrl: 'https://images.pathwise.mock/kumpir.jpg', category: 'food', interests: ['food'], entryFeeTry: 0, avgFoodCostTry: 200, avgVisitMinutes: 35, openingHours: 'Daily 10:00–00:00', isIndoor: false, isSunsetSpot: false, museumPass: false, localTip: 'Loaded baked potato (kumpir) is the signature; pick your toppings.', neighborhood: 'Ortaköy', crowdLevel: 'high', safetyScore: 85, isSoloVerified: true, transitNoteBefore: 'The row runs off Ortaköy square, 1 min from the mosque.', insiderTip: 'Every stall sells the same baked potato at the same price, so pick by whichever topping counter looks freshest — and say "hepsinden" if you want a bit of everything.', photoGoldenHour: 'After dark, when the whole row is neon-lit and at its busiest.', priceTier: 2, emoji: '🥔', source: 'Google Places' },
  { placeId: 'ChIJ-besiktas-yildiz-park', name: 'Yıldız Park', hub: 'besiktas-bogaz', lat: 41.0501, lng: 29.0125, rating: 4.6, reviewCount: 42800, photoUrl: 'https://images.pathwise.mock/yildiz-park.jpg', category: 'nature', interests: ['nature', 'photo'], entryFeeTry: 0, avgFoodCostTry: 130, avgVisitMinutes: 60, openingHours: 'Daily 07:00–22:00', isIndoor: false, isSunsetSpot: true, museumPass: false, localTip: 'Climb to Malta Köşkü café for a hilltop Bosphorus panorama.', neighborhood: 'Beşiktaş', crowdLevel: 'low', safetyScore: 87, isSoloVerified: true, transitNoteBefore: 'A 12-min uphill walk from Beşiktaş square, or a short taxi to the upper gate.', insiderTip: 'Keep climbing to the Malta Köşkü pavilion café — the terrace has a Bosphorus view that most day-trippers never walk far enough uphill to find.', photoGoldenHour: 'Autumn afternoons, when the woodland turns and the light comes in low.', priceTier: 1, emoji: '🌲', source: 'IBB Open Data' },
  { placeId: 'ChIJ-besiktas-fishmarket', name: 'Beşiktaş Fish Market', hub: 'besiktas-bogaz', lat: 41.0426, lng: 29.0064, rating: 4.5, reviewCount: 19700, photoUrl: 'https://images.pathwise.mock/besiktas-fishmarket.jpg', category: 'market', interests: ['market', 'food'], entryFeeTry: 0, avgFoodCostTry: 480, avgVisitMinutes: 55, openingHours: 'Daily 09:00–22:00', isIndoor: false, isSunsetSpot: false, museumPass: false, localTip: 'Pick a fish at the stalls and a nearby lokanta will cook it for you.', neighborhood: 'Beşiktaş', crowdLevel: 'medium', safetyScore: 85, isSoloVerified: true, transitNoteBefore: 'A 3-min walk inland from Beşiktaş pier, behind the bus terminus.', insiderTip: 'The market hall itself is small — the point is the ring of tiny meyhanes around it, where you buy the fish at a stall and they cook it for you for a small cover.', photoGoldenHour: 'Late afternoon, when the day’s catch is laid out and the lamps come on.', priceTier: 2, emoji: '🐟', source: 'Google Places' },
  { placeId: 'ChIJ-besiktas-bebek-sahil', name: 'Bebek Seaside', hub: 'besiktas-bogaz', lat: 41.0776, lng: 29.0433, rating: 4.7, reviewCount: 51200, photoUrl: 'https://images.pathwise.mock/bebek-sahil.jpg', category: 'nature', interests: ['nature', 'photo', 'food'], entryFeeTry: 0, avgFoodCostTry: 260, avgVisitMinutes: 50, openingHours: 'Always open', isIndoor: false, isSunsetSpot: true, museumPass: false, localTip: 'Grab a coffee at Bebek Kahve and sit on the sea wall.', neighborhood: 'Bebek', crowdLevel: 'medium', safetyScore: 91, isSoloVerified: true, transitNoteBefore: 'Bus north along the shore road from Beşiktaş, about 15 min.', insiderTip: 'Walk the promenade from Bebek Park up to the Rumeli Hisarı fortress — a flat 20 minutes past the best waterfront mansions in the city, and free.', photoGoldenHour: 'Sunrise, with the Asian shore lit across the water and the bay still glassy.', priceTier: 3, emoji: '⛵', source: 'Google Places' },
];

export const PLACES_BY_ID: Record<string, Place> = Object.fromEntries(
  PLACES.map((p) => [p.placeId, p]),
);
