import { test, expect, type Page } from '@playwright/test';
import { dismissWelcome } from './helpers/welcome';

/**
 * Audio guide.
 *
 * The narration is generated by a language model, so the wording differs run
 * to run and cannot be asserted. What can be asserted is everything around it:
 * that a place with no Wikipedia article gets no player at all, that the
 * script is shown as text and not only spoken, that its source is named, and
 * that the place name is the one Istanbul uses.
 */

async function signUp(page: Page, tag: string): Promise<void> {
  await page.goto('/auth');
  await page.getByPlaceholder('Aylin Demir').fill('Narration Tester');
  await page
    .getByPlaceholder('you@example.com')
    .fill(`e2e_${tag}_${Date.now()}@std.antalya.edu.tr`);
  await page.getByPlaceholder('At least 8 characters').fill('secret123');
  await page.getByRole('button', { name: /Create account/i }).click();
  await page.waitForURL(/\/dashboard$/, { timeout: 20_000 });
  await dismissWelcome(page);
}

/** Put a place into the day and open its story modal. */
async function openStory(page: Page, search: string, name: RegExp): Promise<void> {
  await page.getByPlaceholder(/Search a place/i).fill(search);
  await expect(page.getByRole('button', { name }).first()).toBeVisible({
    timeout: 15_000,
  });
  await page.getByRole('button', { name: '➕ Add' }).first().click();

  const row = page
    .locator('li')
    .filter({ has: page.locator('h3', { hasText: name }) })
    .first();
  await expect(row).toBeVisible({ timeout: 20_000 });
  await row.getByRole('button', { name: /Read Local Story/i }).click();
}

test('a place with a Wikipedia article gets a player, sourced and readable', async ({
  page,
}) => {
  await signUp(page, 'narr');
  await openStory(page, 'Hagia Sophia', /^Hagia Sophia\b/);

  const player = page.getByTestId('narration-player');
  await expect(player).toBeVisible({ timeout: 40_000 });

  // The script is on the page, not only in the audio: someone who cannot hear
  // it, or is somewhere they cannot play it, still gets the guide.
  const script = page.getByTestId('narration-script');
  await expect(script).toBeVisible();
  expect((await script.textContent())?.length ?? 0).toBeGreaterThan(200);

  // Named source — the narration is a rewording of a citable article, and
  // saying which one is what makes it checkable.
  await expect(player).toContainText(/Wikipedia/i);

  // The place name is the one on the street sign, not a translation. The
  // model transliterates it if left unchecked, so the server drops any script
  // that loses the name — this asserts the guard is doing its job.
  await expect(script).toContainText(/Ayasofya/);

  await expect(page.getByTestId('narration-toggle')).toBeVisible();
});

test('a place with no article shows no player at all', async ({ page }) => {
  await signUp(page, 'narrnone');

  // Wait for the server's answer rather than for the absence of an element:
  // the player renders nothing while loading, so a bare count-zero assertion
  // would pass before the request had even come back.
  const answered = page.waitForResponse(
    (r) => r.url().includes('/narration'),
    { timeout: 40_000 },
  );

  // A café: no Wikipedia article, so there is nothing honest to narrate. The
  // tempting failure is a narration assembled from the name and category.
  await openStory(page, 'Baylan', /^Baylan Pastanesi\b/);

  const body = (await (await answered).json()) as { narration: unknown };
  expect(body.narration).toBeNull();
  await expect(page.getByTestId('narration-player')).toHaveCount(0);
});
